name: pensieve
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  provider: ^6.0.0
  uuid: ^3.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  msix: ^3.7.0

msix_config:
  display_name: "The Pensieve"

flutter:
  uses-material-design: true

  assets:
    - assets/pensieve.gif
